### ISSUE TITLE
Hardcoded api_key, api_hash

### ISSUE THREAD

**Issue by nkonin** [uniborg/uniborg#12]
It seems someway awkward.

https://github.com/uniborg/uniborg/blob/773190dd1e6df014591ed0b5fc738850506b6e2b/uniborg/uniborg.py#L31-L33

**Comment by Lonami** [comment]
It's nice and convenient that it JustWorks™, but you're right it's not clean and there should be a way to encourage using your own.

**Comment by Streetwalrus** [comment]
This is by design. You can pass your own API keys if you want, we're using the keys from another client to make things easier to use.
