### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by nkonin** [uniborg/uniborg#13]
`/Users/nkonin/Documents/projects/uniborg/venv/lib/python3.6/site-packages/telethon/__init__.py:4: UserWarning: The telethon-aio package has been deprecated since the version 1.0 of the library, which now uses asyncio. Run "pip uninstall telethon-aio" and "pip install telethon" instead. See the main repository for more information: https://github.com/LonamiWebs/Telethon
  'The telethon-aio package has been deprecated since the version 1.0 '`

**Comment by Streetwalrus** [comment]
You're not using the right version of telethon. Read the message again.

**Comment by nkonin** [comment]
@Streetwalrus it's version from `requirements.txt`

**Comment by Streetwalrus** [comment]
My bad, I've overlooked that when porting to current telethon.
