### ISSUE TITLE
IOLoop blocking code

### ISSUE THREAD

**Issue by nkonin** [uniborg/uniborg#15]
https://github.com/uniborg/uniborg/blob/c1e3b2f3c351b38370972ae1150a868fb64761b7/stdplugins/headpat.py#L31-L35

This request is executed synchronously.
It's probably worth it to rewrite it in an asynchronous style.

**Comment by Lonami** [comment]
It's only done once. Having a external dependency like `aiohttp` just for this seems… unnecessary.

**Comment by Streetwalrus** [comment]
Long term goal is to get rid of that plugin altogether, it's going to be handled much better in another bot.

**Comment by nkonin** [comment]
@Lonami How about doing this request when loading the plugin so that it does not affect the bot at an unexpected moment?

**Comment by Lonami** [comment]
We *could* but then it would idle the bot even if the plugin never gets used. Also… slow down in unexpected moment… For how long? A second? No big deal.

**Comment by Streetwalrus** [comment]
*whispers something about lazy evaluation*

**Comment by Lonami** [comment]
Fixed with https://github.com/uniborg/uniborg/commit/e809a721b44edf0ecca912fc55e65562f39299b6.
