### ISSUE TITLE
Istant ban when using a number

### ISSUE THREAD

**Issue by FibelSistine** [uniborg/uniborg#18]
Without any modification, just running as it is, after some seconds telegram banned 2 phone numbers.

**Comment by Streetwalrus** [comment]
Telethon issue.

**Comment by Lonami** [comment]
For what is worth, it's a *Telegram's* issue. They decide who to ban. Some countries and phone numbers are more prone to be banned. Ask support to unban you.

**Comment by FibelSistine** [comment]
thank you, i try to ask then
